java.lang.ExceptionInInitializerError: null 	at no.nav.helse.soknad.SøknadValidatorKt.validerK9Format(SøknadValidator.kt:250) 	at no.nav.helse.soknad.SøknadService.registrer(SøknadService.kt:47) 	at no.nav.helse.soknad.SøknadService.invokeSuspend(SøknadService.kt) 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) 	at io.netty.util.concurrent.SingleThreadEventExecutor.run(SingleThreadEventExecutor.java:997) 	at io.netty.util.internal.ThreadExecutorMap.run(ThreadExecutorMap.java:74) 	at io.ktor.server.netty.EventLoopGroupProxy.create-1-0(NettyApplicationEngine.kt:288) 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 	at java.base/java.lang.Thread.run(Thread.java:833) Caused by: javax.validation.ValidationException: HV000183: Unable to initialize 'javax.el.ExpressionFactory'. Check that you have the EL dependencies on the classpath, or use ParameterMessageInterpolator instead 	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.buildExpressionFactory(ResourceBundleMessageInterpolator.java:199) 	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.<init>(ResourceBundleMessageInterpolator.java:94) 	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.getDefaultMessageInterpolator(AbstractConfigurationImpl.java:573) 	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.getDefaultMessageInterpolatorConfiguredWithClassLoader(AbstractConfigurationImpl.java:822) 	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.getMessageInterpolator(AbstractConfigurationImpl.java:483) 	at org.hibernate.validator.internal.engine.ValidatorFactoryImpl.<init>(ValidatorFactoryImpl.java:154) 	at org.hibernate.validator.HibernateValidator.buildValidatorFactory(HibernateValidator.java:38) 	at org.hibernate.validator.internal.engine.AbstractConfigurationImpl.buildValidatorFactory(AbstractConfigurationImpl.java:451) 	at javax.validation.Validation.buildDefaultValidatorFactory(Validation.java:103) 	at no.nav.k9.søknad.ytelse.psb.v1.PleiepengerSyktBarnSøknadValidator.<clinit>(PleiepengerSyktBarnSøknadValidator.java:19) 	... 14 common frames omitted Caused by: java.lang.NoClassDefFoundError: javax/el/ELManager 	at org.hibernate.validator.messageinterpolation.ResourceBundleMessageInterpolator.buildExpressionFactory(ResourceBundleMessageInterpolator.java:191) 	... 23 common frames omitted Caused by: java.lang.ClassNotFoundException: javax.el.ELManager 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) 	at java.base/jdk.internal.loader.ClassLoaders.loadClass(ClassLoaders.java:188) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) 	... 24 common frames omitted